### ISSUE TITLE
Is it possible more than 99 results?

### ISSUE THREAD

**Issue by ctoveloz** [JeffpanUK/GoogleBot#1]
Hi, Thanks fo the bot.
I try a number results more of 99 but the max is 99 is possible more ?

Thanks

**Comment by JeffpanUK** [comment]
@ctoveloz  Thanks for your issue. Now it can show more than 99 results. 
Also, Google will omit similar and irrelevant results sometimes, and you can ignore this by adding "-d 1" option.

**Comment by JeffpanUK** [comment]
implemented in changeset: 83bfb2091fdda0fc512b4006b85923f01e55cfde

**Comment by ctoveloz** [comment]
Thanks, works only have a little bug.
Change this line
`parser.add_argument("-r", "--results", action="store", dest="results", type = int, default='results.txt', help='searching results')`
to
`parser.add_argument("-r", "--results", action="store", dest="results", type = str, default='results.txt', help='searching results')`
work for me :)
After i will pass for you another suggestions if you can implement :D

**Comment by JeffpanUK** [comment]
@ctoveloz thanks. I've merged your pr.
